source/javascripts/app/_toc.js, source/layouts/apitwocolumn.erb, source/stylesheets/screen.css.scss
Lock header in place, fix nav links to not appear underneath header.
@bc-mkatz @becomevocal @bc-AlyssNoland
=> Fix nav stuff

source/layouts/apitwocolumn.erb, source/layouts/twocolumn.erb
@bc-AlyssNoland @bc-mkatz @becomevocal
=> Place target link underneath header

source/includes/_api_customer_login.md
All 3 examples are now displayed directly in the doc (with syntax highlighting), but also still hyperlinked to the live repo’s.
=> Updated _api_customer_login.md

source/layouts/apitwocolumn.erb, source/layouts/changelog.erb, source/layouts/home.erb, source/layouts/layout.erb, source/layouts/support.erb, source/layouts/twocolumn.erb, source/stylesheets/_custom.scss
Create Account and Login links corrected for launch 
Added width constraints to _custom.scss for API pages
=> Revisions to top nav links & api CSS width restraints

source/includes/_api_objects_product.md
Reformatted enums to 1 value per row, as Jay Mendoza suggested. But
whole page was incoherent, so did complete rewrite. Added outbound
links and consistent sentence structure/formatting.
=> Rewrote Product > Properties

source/includes/_changelog_2016.md, source/includes/_themes_global_variables.md
These are minor updates to properties tables and changelog. Let’s merge, then I’ll hit restructuring in a separate branch.
=> Content additions

source/api/index.html.md, source/includes/_api_CRUD_blog_posts.md, source/includes/_api_approval-requirements.md, source/includes/_api_browsers.md, source/includes/_api_callback.md, source/includes/_api_completing_reg.md, source/includes/_api_guides_curl_quickstart.md, source/includes/_api_load.md, source/includes/_api_objects_blog_post.md, source/includes/_api_webhooks_getting_started.md, source/includes/_changelog_2016.md, source/themes/blueprint/index.html.md
Open/ongoing branch to groom & re-link content, to conform our left nav to the existing/live Dev Portal’s navigation.
=> Toc+link rebuilds 4

source/api/index.html.md, source/themes/blueprint/index.html.md, source/themes/index.html.md
Changed navigational blocks to H2/H3 headers per the design discussed
with Nate Stewart and Michael Katz
=> Removal of blocks, addition of H2/H3 callouts

source/layouts/twocolumn.erb, source/stylesheets/_custom.scss
=> Fixed a typo and corrected hero image css

source/CNAME, source/layouts/_navbar.html.erb, source/robots.txt, source/stylesheets/_navbar.scss
- Changed cname file to correct subdomain
- Revised robots.txt for launch
- Corrected alignment of logo in navbar
- Correct URI in navbar for myapps/developer portal
=> Cname changes for dev docs migration 

source/includes/_api_CRUD_blog_posts.md, source/includes/_api_CRUD_blog_tags.md, source/includes/_api_CRUD_gift_certificates.md, source/includes/_api_CRUD_redirects.md, source/includes/_api_CRUD_time.md, source/includes/_api_objects_blog_post.md, source/includes/_api_objects_country.md, source/includes/_api_objects_coupon.md, source/includes/_api_objects_customer.md, source/includes/_api_objects_order.md, source/includes/_api_objects_payment_method.md, source/includes/_api_objects_product.md, source/includes/_api_objects_redirect.md, source/includes/_api_objects_shipping_method.md, source/includes/_api_objects_store_information.md, source/includes/_api_objects_tax_class.md, source/includes/_api_objects_webhook.md, source/includes/_api_webhooks_getting_started.md, source/includes/_changelog_2016.md
Ongoing matching of the live Dev Portal’s structure – adding, sorting, retagging, and grooming heads to rebuild the Slate TOC in the same order.
=> TOC cleanup

source/includes/_themes_understanding.md, source/themes/index.html.md
Inserted `- themes_store_wide_variables` 3x. The extra 2x are
placeholders for Panels/Variables/Snippets files to be added individually.
=> Themes > TOC initial build

source/api/index.html.md, source/includes/_api.md, source/includes/_api_browsers.md, source/includes/_api_callback.md, source/includes/_api_faqs.md, source/includes/_api_registration.md, source/includes/_api_root_oauth.md, source/includes/_api_status_codes.md, source/includes/_api_webhooks_getting_started.md
=> Ongoing links corrections

source/api/index.html.md, source/includes/_api_callback.md, source/includes/_api_load.md, source/includes/_api_multi-user.md, source/includes/_api_registration.md
Also appends the word “Documentation” to 2 heads in the file below,  at JZON’s behest.
#	source/api/index.html.md
=> Links fixes 10/3/16

source/api/v2/index.html.md, source/includes/_api.md, source/includes/_api_CRUD_blog_tags.md, source/includes/_api_CRUD_customers_addresses.md, source/includes/_api_approval-requirements.md, source/includes/_api_clients.md, source/includes/_api_completing_reg.md, source/includes/_api_guides_curl_quickstart.md, source/includes/_api_guides_oauth_transition.md, source/includes/_api_legacy_basic_auth.md, source/includes/_api_objects_brand.md, source/includes/_api_objects_product.md, source/includes/_api_rate-limits_oauth.md, source/includes/_api_req_headers.md, source/includes/_api_response_headers.md, source/includes/_api_scopes.md, source/includes/_api_ui_constraints.md, source/includes/_api_webhooks_getting_started.md
and also too, for the head of API > v2.
=> Links reset/fixes for API > Basics

source/includes/_api_clients.md, source/includes/_api_customer_login.md, source/includes/_api_objects_store_information.md, source/includes/_api_objects_tax_class.md
Ongoing branch to correct fictitious links within `/api/v2/` subdirectory.
=> API > v2 link fixes

source/includes/_api_media_types.md, source/includes/_api_response_headers.md, source/includes/_api_webhooks_getting_started.md, source/stylesheets/_navbar.scss
A hack that uses px – but it behaves on both Chrome & Firefox, without introducing new artifacts. Fails if I try relative units. I’d welcome help with relative-units refactoring, or with at least tweaking the absolute breakpoints.
=> Logo alignment, Take 3

source/includes/_api_legacy_basic_auth.md
First commit on this PR updates a control-panel label. (Thanks JZON.) Future commits will update the Store Information resource for BIG-27949.
=> Updated CP references

source/api/index.html.md, source/themes/blueprint/index.html.md, source/themes/blueprint/layouts/index.html.md, source/themes/blueprint/panels/index.html.md, source/themes/blueprint/snippets/index.html.md, source/themes/index.html.md
Above Webhooks Overview, in API [root] > left nav.
=> Client Libraries promoted

source/includes/_api_CRUD_pages.md, source/includes/_api_objects_order.md, source/includes/_api_objects_page.md, source/includes/_themes_syntax.md, source/includes/_themes_variables_email.md, source/themes/blueprint/index.html.md
Added file within Themes > Blueprint > Basics, to cover variables
available within Email Templates. Adjusted index to add this file &
correct duplicate “Global Variables” entries = broken navigation.
=> Email variables: MERC-1368

source/api/v2/index.html.md, source/includes/_api_CRUD_pages.md, source/includes/_api_objects_blog_post.md, source/includes/_api_objects_page.md, source/includes/_changelog_2016.md
Final content files; addition to index/left nav; addition to intro text; 3 new Changelog entries. Approved by Lawrence Willkowske – let’s please merge and deploy.
=> Api 369 - Pages API

source/includes/_themes_layouts_packing_slip_print.md
Added %%GLOBAL_CustomerEmail%% variable. This will make Alyss happy.
=> Layouts > Packing Slip Print update

source/includes/_api_webhooks_getting_started.md, source/includes/_changelog_2016.md
…to Webhooks overview, and to changelog. For
https://jira.bigcommerce.com/browse/WEBHOOKS-57.
=> Added `category` Webhooks

source/includes/_api_CRUD_customers.md
For DEV-5: To `Create a Customer` > read-only properties, added `form_fields` array.
=> Customer read-only update

source/layouts/_feedbackme_script.erb, source/stylesheets/jquery.feedback_me.css
Made form 50 px deeper, to fit a “Your name?” field onto bottom of corresponding
Wufoo form.
=> +50 px -> feedback form, please merge

source/includes/_api_CRUD_countries.md, source/includes/_api_CRUD_coupons.md, source/includes/_api_CRUD_customers.md, source/includes/_api_objects_customer.md, source/includes/_api_objects_customer_address.md
Let’s please merge & deploy this. Updated `Update a Coupon` > `Requirements` with JZON’s discoveries/advice. Also, copy-edited several related files with broken tagging or headings.
=> API-244 + copy edits

source/api/v2/index.html.md, source/includes/_api_CRUD_currencies.md, source/includes/_api_objects_currency.md
This is for API-103/API-565. Please review the content – especially the Object table: Several descriptions are guesses, and one punts with the placeholder “(Description to follow.)”
=> Added Currencies API

source/includes/_api_objects_currency.md, source/includes/_changelog_2016.md
Adds missing description to Object Properties table, + changelog entry.
=> Currency API wrap-up

source/api/v2/index.html.md, source/includes/_api_CRUD_orders.md, source/includes/_api_order_products_array.md
Restoring missing docs page, per API-587.
=> Restore order products array

source/includes/_api_CRUD_orders.md, source/includes/_themes_checkout_styling.md
In Blueprint > Checkout Styling, corrected malformed link to CSS
example.
Other changes in this PR will incorporate stewed copy updates from John Nichols.
=> Fixes (crowdsourced)

source/api/v2/index.html.md, source/includes/_api.md, source/includes/_api_approval-requirements.md, source/includes/_api_completing_reg.md, source/includes/_api_guides_oauth_transition.md, source/includes/_api_legacy_basic_auth.md, source/includes/_api_root_oauth.md, source/includes/_changelog_2016.md, source/stylesheets/_custom.scss
Incorporated John Nichols’ updates to API > Basics content.
=> API Basics: DEV-13 updates

source/layouts/404.erb, source/layouts/_navbar.html.erb
Fixes https://github.com/bigcommerce-labs/slate/issues/85
=> Fix "Create account" button in FF

source/javascripts/lib/_lunr.js
Small performance gains from updating away from version 0.5.7 to 0.7.2
Documentation of changes available at https://github.com/olivernn/lunr.js/blob/master/CHANGELOG.mdown. Changes have been tested locally to ensure current search isn't interrupted.
=> Updated lunr.js version to 0.7.2

source/javascripts/app/_search.js, source/layouts/apitwocolumn.erb, source/layouts/layout.erb, source/layouts/theme2column.erb, source/layouts/themetop3button.erb, source/layouts/twocolumn.erb, source/stylesheets/screen.css.scss
Add input button on each layout that uses search to enable mobile and desktop users to reset search without esc key or deleting
Added comment on javascript change in _search.js
Add javascript to get input/reset button working.
=> Adds reset search button for mobile and desktop users

deploy.sh
Bundle install is required to successfully deploy.
=> TOOLING-1182: Add bundle install

source/layouts/support.erb
Also correctly escaped some html that was caused GH errors.
=> Updated support page to link and promote developer forums

source/drafts/index.html.md, source/includes/_add-to-cart-urls.md, source/includes/_changelog_2016.md, source/layouts/support.erb
Adding this under hidden `/drafts/` for Nathan’s OK, before publishing
it for reals under “Building Storefront Apps.”
=> Add-to-Cart URLs

source/api/index.html.md, source/drafts/index.html.md, source/includes/_add-to-cart-urls.md
Incorporated Nathan B.’s corrections; moved to public `/api/` root
directory.
=> Publish Add-to-Cart URLs

source/drafts/index.html.md, source/includes/_api_CRUD_shipping_zones.md, source/includes/_api_objects_shipping_zone.md, source/includes/_changelog_2016.md
(Hidden) rough structure for BIG-29396: `/drafts/` > Shipping Zones/Methods.
=> BIG-29396 hidden draft

source/layouts/_navbar.html.erb, source/stylesheets/_custom.scss
Added styles to custom.scss and html to _navbar.html.erb to create dropdown menus that appear on hover. 
Run locally
Visit localhost:4567
Hover over API or Themes
None
=> Added dropdowns for API and themes navigation

source/stylesheets/_custom.scss, source/stylesheets/_navbar.scss, source/stylesheets/screen.css.scss
Corrected list and a tag elements that had had their styles altered by my previous changes to add drop down menus
Check side nav styling on desktop for spacing and left alignment
=> Corrected css from navbar dropdown changes

source/api/index.html.md, source/changelog/index.html.md, source/includes/_api.md, source/includes/_api_objects_blog_post.md, source/includes/_api_objects_shipping_zones_method.md, source/includes/_changelog_2017.md
=> Changelog fix again

source/includes/_api_2_quick_starts.md
=> API Quick Start: 1-word fix

source/includes/_api_basic_auth_tokens.md, source/includes/_api_oauth_tokens.md
Tweaks to heading and left nav, plus more OAuth propaganda, at Nate’s
request.
=> OAuth/Basic Auth rewording

Gemfile, Gemfile.lock, source/layouts/apitwocolumn.erb, source/layouts/layout.erb, source/layouts/theme2column.erb, source/layouts/themetop3button.erb, source/layouts/twocolumn.erb, source/stylesheets/screen.css.scss
changed "x" to icon
Use search on /api and type in webhooks. Click X icon to reset the form and clear results/highlighting
=> Changed X to reset icon

source/drafts/index.html.md, source/includes/_api_basic_auth_tokens.md, source/includes/_api_legacy_basic_auth.md, source/includes/_api_oauth_tokens.md, source/includes/_changelog_2016.md, source/includes/_changelog_2017.md, source/includes/_v3-catalog-sample-script-xform.md
Adds: (1) Stencil `template_file` property’s deprecation and
replacement; and (2) Stencil support for Optimized One-Page Checkout.
=> Changelog updates

source/drafts/index.html.md, source/includes/_api_basic_auth_tokens.md, source/includes/_api_oauth_tokens.md, source/includes/_v3_catalog_customer_complete.md
* Imported v3 file to Slate .md, within `/includes/`.
* Referenced it in `/drafts/index.html.md`.
* Promoted OAuth, Basic-Auth heads to h1’s, to improve their left-nav
visibility.
A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
Provide as much information as you can about how you tested, how another developer can test, and how a Quality Engineer can confirm.
Add links to any relevant tickets and documentation.
- [Link 1](http://example.com)
- ...
Attach images or add image links here.
Are there any requirements that need to be taken care of before this can be released? 
Please add a checklist using the following syntax for release …
=> v3 updates: metafields, Subscriber

source/stylesheets/_custom.scss, source/stylesheets/_variables.scss
See title
Verify no visual/color changes between production and local testing
=> Cleaned up custom.scss to use color variables

source/stylesheets/screen.css.scss
=> Corrected h1 font size

README.md, data/openapi-cart.yaml, data/openapi-catalog.yaml, data/openapi-orders.yaml, source/api/v3/openapi-cart.html.md, source/api/v3/openapi-catalog.html.md, source/api/v3/openapi-orders.html.md, swagger2md.js
A script that will take raw Swagger files and convert them to slate-friendly markdown for easy including into the docs.
Run `node swagger2md.js` from project root, with valid swagger .yaml files in source/api/v3
You should expect any .yaml.md files in the directory to be deleted and new generated files to be created in their place from the valid .yaml files.
Must `npm install` these first:
widdershins
js-yaml
The intent is that changes to the raw .yaml files can be committed, after which this script can be run and the updated .yaml.md files are then committed and deployed.
ping @bc-AlyssNoland @becomevocal
=> DEV-22 - Swagger to slate markdown script for V3

.gitignore, source/api/v2/index.html.md
=> Removed 3 duplicate files from api v2 page

source/layouts/_mailchimp.html.erb, source/layouts/apitwocolumn.erb, source/layouts/layout.erb, source/layouts/theme2column.erb, source/layouts/themetop3button.erb, source/layouts/twocolumn.erb, source/stylesheets/_buttons.scss, source/stylesheets/_custom.scss
See title. Also removed toc footers in place of this form. 
Verify email is sent to mailchimp when using form
=> Added mailchimp signup form

source/api/guides/index.html.md, source/includes/_changelog_2017.md
- Updated Changelog with four February ’17 entries.
- Streamlined Guides section’s introductory text, for easier/faster reading.
=> Changelog + Guides updates

source/includes/_api_customer_login.md
customer_id should be int, not str
=> Fix incorrect docs.

source/includes/_api_root_oauth.md
=> Correct code snippet for managing user sessions

source/includes/_api_partners.md
- Updated Sandbox Store setup instructions, to match new procedure already documented on Partner Portal FAQ. This update is at Nell's request.
=> Content updates: Sandbox Store & Shipping
