bigcommerce-labs/dev-docs

source/includes/_api_approval-requirements.md, source/includes/_api_ui-constraints.md, source/stylesheets/screen.css.scss
Added "App Req's" + "UI Constraints" pages. (Not yet linked to index page or left nav.)
In screen.css.scss, resolved faux conflict between .themes .content vs. .vtwo-links selectors.
=> API content + CSS sync

source/includes/_api_CRUD_store_information.md, source/includes/_api_objects_category.md, source/includes/_api_objects_store_information.md, source/includes/_changelog_2016.md
Changed “Cateogry” to “Category”.
=> Category object – spelling fixes

source/includes/_changelog_2016.md
This just updates `_changelog_2016.md` to sync with the `shipping_provider` field’s announcement in the live Dev Portal on 6/16/16.
=> Changelog 2016 sync

source/stylesheets/_custom.scss, source/stylesheets/_navbar.scss
Not my proudest work, but hey.
- Assigned new widths for each header section so they never overflow
- Fixed heights of header on mobile
- made header full width
- Logo section is now only as wide as the sidebar nav
- New breakpoint which sets the logo section width to sidebar width when sidebar is open by default. Otherwise reverts to previous styles.
@bc-AlyssNoland
=> Various CSS fixes to the responsive navbar

source/includes/_api_registration.md, source/stylesheets/_variables.scss, source/stylesheets/screen.css.scss
On `aside.notice`, lightened blue background to a tint of BC 2016
branded blue – to make links, code, etc., readable against the bgd.
On `aside.warning`, corrected border-rule color to match bold-heading
color.
=> Callouts – final tweaks

source/includes/_api_CRUD_categories.md, source/includes/_api_CRUD_redirects.md, source/includes/_api_approval-requirements.md, source/includes/_api_callback.md, source/includes/_api_load.md, source/includes/_api_registration.md, source/includes/_api_root.md, source/includes/_api_root_basic_auth.md, source/includes/_api_root_oauth.md, source/includes/_api_scopes.md, source/includes/_api_webhooks_getting_started.md, source/stylesheets/screen.css.scss
Changed all `aside*` heads from `::first-line` pseudo-elements to
optional `span`'s. Corrected icons’ color for `aside.warning:before`. Retagged some `aside` paragraphs to verify good results. This might really be final re-styling for callouts.
=> Peace at last for callouts

source/includes/_api_load.md, source/includes/_api_objects_product_configurable_field.md, source/includes/_api_objects_product_googleproductsearch.md, source/stylesheets/screen.css.scss
* Adds Nate’s CSS to create uniform table-border widths.
* Stray content updates/fixes that arrived at the same time.
* Good, clean point to merge this back in.
Here's the golden CSS, from commit below:
```
.content table {
display: table !important;
margin-left: 28px;
width: 75% !important;
min-width: initial !important;
}
```
=> Table+content updates

source/includes/_api_CRUD_products.md
Added  `id` as a read-only property – correction from Jason Zamora.
=> "Create a Product" correction

source/includes/_themes_global_variables.md
At Adam Ferenzi’s request. Can’t match on Contentful because of
https://jira.bigcommerce.com/browse/API-216 blockage.
=> Added `%%GLOBAL_CustomerGroupId%%` to Themes > Global Variables

source/layouts/apitwocolumn.erb, source/stylesheets/_buttons.scss, source/stylesheets/_custom.scss, source/themes/blueprint/index.html.md, source/themes/index.html.md
Commented out 2nd row of Themes buttons, as too
intrusive. Added single “Themes” button in widened single row,
using several CSS hacks. If we like the general flow, tweak/refactor later.
=> 4 button row re-skin

source/includes/_api_guides_curl_quickstart.md
”cURL QuickStart" copy edits: Changed subheads to title case; broke up stacked heads. This solidifies “Building Basic-Auth Apps” left nav. Still need to reset links within body text.
=> Final "Basic Auth" copy edit

source/api/index.html.md, source/api/v2/index.html.md, source/api/v3/index.html.md, source/changelog/index.html.md, source/includes/_api_CRUD_orders.md, source/includes/_api_CRUD_payments_methods.md, source/includes/_api_CRUD_products_options.md, source/includes/_api_CRUD_products_product_options.md, source/includes/_api_CRUD_webhooks.md, source/includes/_api_faqs.md, source/includes/_api_legacy_basic_auth.md, source/includes/_api_objects_brand.md, source/includes/_api_objects_order.md, source/includes/_api_objects_payment_method.md, source/includes/_api_objects_product.md, source/includes/_api_objects_product_product_option.md, source/includes/_api_objects_webhook.md, source/themes/blueprint/index.html.md, source/themes/index.html.md
Moved "Building OAuth/Basic-Auth Apps" to API > root. Resumed reorganizing API > v2 > TOC and TOC footer. The `index.html.md` file now completely conforms to legacy Dev Portal structure. However, within the `include` files, _many_ heads still need to be demoted one level, to get the left TOC pane to render the proper structure.
=> Moved "Building Apps" to root

source/api/v2/index.html.md, source/includes/_themes_understanding.md, source/stylesheets/screen.css.scss, source/themes/index.html.md
Removed `*.md` from `/api/v2/` includes references. Separated out
Themes > landing page/screen as new `_themes_understanding.md` file.
Adjusted CSS > `fake-h2` & `fake-h3` styles (to look like h2 & h3) &
applied those styles. SLOPPY CSS, should REFACTOR later.
=> Last api index fixes + Themes TOC top fixes

source/javascripts/lib/_lunr.js
Try: Cut the “similarityBoost” on exact search keys by 9/10. Lunr’s
site claims this should reveal matches for non-adjacent word pairs used
as search keys.
=> Fuzzier Search test

source/layouts/404.erb
Alignment between API vs. Themes rows is hacked – feel free to refactor
– but here’s the result I’m proposing.
=> 404 page w/more back links

index.html.md, source/changelog/index.html.md, source/javascripts/app/_search.js, source/layouts/apitwocolumn.erb, source/layouts/theme2column.erb, source/layouts/themetop3button.erb
Removes javascript call that is unused & doesn't begin highlighting search term until string is 3 or more characters long.
=> Performance improvement for client-side js search

source/includes/_api_CRUD_blog_posts.md, source/includes/_api_CRUD_orders_shipments.md, source/includes/_api_CRUD_shipping_zones_methods.md, source/includes/_api_objects_blog_post.md, source/includes/_api_objects_order_shipment.md
Added missing descriptions. Clarified that `shipping_provider` is
required in POST requests, to avoid counterintuitive fallback/default
behavior.
=> Order > Shipment (API-663) fixes

Gemfile, Gemfile.lock, config.rb, data/site.yml, source/robots.txt, source/robots.txt.erb, source/sitemap.txt.erb, source/sitemap.xml.builder
Allow middleman to generate a sitemap for us based on existing directory structures. 
Verify /sitemap.txt and /sitemap.xml show the subdirectories and that robots.txt dictates what should be crawled by bots
- [DEV-20](https://jira.bigcommerce.com/browse/DEV-20)
=> DEV 20: Added functionality to generate sitemap

source/includes/_api_objects_coupon.md, source/includes/_api_objects_order.md, source/includes/_api_objects_order_status.md
Reset fictitious, broken, or vague links. Rewrote descriptions for brevity and readability.
=> Orders & Coupons updates

source/api/guides/index.html.md, source/api/index.html.md, source/includes/_api_basic_auth_tokens.md, source/includes/_api_guides_curl_quickstart.md, source/includes/_api_oauth_tokens.md, source/includes/_tut_postman_oauth.md, source/layouts/404.erb, source/layouts/_navbar.html.erb, source/layouts/apitwocolumn.erb, source/stylesheets/_custom.scss
Moving quickstart/guide content to respective directory for SEO benefit and discoverability within the site
Verify images, links, and content is available under /api/guides and that navigation dropdown is functional on 404s and all other pages.
=> Created api guides subdir and moved content

source/javascripts/app/_toc.js, source/javascripts/lib/_jquery.tocify.js, source/stylesheets/_custom.scss
Altered _tocify.jquery.js so that divs that create an anchor also add a class. This class is used to style the `divs` with `display:none` so that it doesn't negatively impact page layout. 
- Verify anchors are still working from TOC
- On page complete, TOC shouldn't open unless an anchor was present in the URL
- No odd white space between middle column content
- [DEV-23](http://example.com)
**Previously** (ignore ugly wireframe lines): 
@tekstrand @PascalZajac
=> DEV-23: Altered toc library to eliminate white space created by anchor divs

.gitignore, source/api/v3/openapi-cart.html.md, source/api/v3/openapi-catalog.html.md, source/api/v3/openapi-orders.html.md, swagger2md.js, user_templates/code_http.dot, user_templates/code_java.dot, user_templates/code_javascript.dot, user_templates/code_python.dot, user_templates/code_ruby.dot, user_templates/code_shell.dot
Updated python template to a WIP state with headers
Changed swagger2md.js to:
- remove code sample generation until this can be refined
- change layout file until code samples need to be used
- made a change so it makes use of our templates instead of stock templates included with repo
Regenerated the files based off of these changes. 
Run `node swagger2md.js` and verify no code samples are left
Run `bundle exec middleman rake` and view localhost:4567/api/v3/openapi-catalog.html to verify layout is correctly utilized
=> Updated swagger to md generation

source/includes/_changelog_2017.md, source/includes/_themes_blueprint.md, source/stylesheets/_custom.scss
- Added callout that Blueprint themes are visible in a store’s cp only if acquired before November 2016.
- Rewrote Blueprint text to acknowledge Blueprint's legacy status.
- Added links to Stencil's merchant-oriented and developer docs.
- For Changelog, fixed one 2017 entry and two heading styles.
=> Cp access blurb

source/javascripts/app/_search.js, source/layouts/apitwocolumn.erb, source/layouts/layout.erb, source/layouts/theme2column.erb, source/layouts/themetop3button.erb, source/layouts/twocolumn.erb, source/stylesheets/screen.css.scss
- Removed html5 reset in favor of existing js
- Moved js function into bind which is called fewer times to reduce negative impact to execution speed
- Changed css to use variables and position relative to input box
1. Stand up with `bundle install` and `bundle exec middleman server`
2. Load inside page such as /api
3. Type in search input box
4. Check mobile/tablet sizes 
@tekstrand @bc-brad
=> Reset search button fixes for js and css
